kind: pipeline
name: cicd

steps:
  - name: build
    image: docker/compose
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    environment:
      PLUGIN_HOST:
        from_secret: PLUGIN_HOST
    commands:
      - docker-compose up -d --build

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock